export { EditorDetector }           from './ai/detector';
export { AICommandsManager }        from './ai/commands-manager';
export { AIToggleManager }          from './ai/toggle-manager';
export { TerminalManager }          from './terminal/side-panel';
export { BottomTerminalManager }    from './terminal/bottom-panel';
export { DebugManager }             from '../debug/panel';
export { WordWrapManager }          from '../wordwrap/manager';
export { PanelCommandsManager }     from '../panels/commands';
export { recoverSidePanelState }    from './terminal/startup-recovery';
